// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Webshop.Data;

#nullable disable

namespace Webshop.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Webshop.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Webshop.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Currency")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("QuantityAvailable")
                        .HasColumnType("int");

                    b.Property<bool>("Sale")
                        .HasColumnType("bit");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Currency = 0,
                            Description = "Nestled in a quiet neighborhood, this historic brick house exudes character and potential. Built circa 1920, it has weathered the decades and now awaits a new chapter. The generous corner lot boasts mature trees and ample green space.\nCalling all DIY enthusiasts! If you’re passionate about restoration and have a vision for transforming neglected gems, this is your canvas. The house retains its original brick facade, showcasing timeless craftsmanship. Inside, the layout includes three bedrooms, a cozy living room, and a vintage kitchen. Expect to tackle electrical updates, plumbing repairs, and perhaps even structural adjustments. Bring your imagination—open up the floor plan, add a sunroom, or create a dreamy attic retreat.\nThe brickwork tells stories of bygone eras, waiting for your TLC. The living room fireplace could be a cozy focal point once restored. Imagine sipping coffee on the porch swing, watching the seasons change. With the right renovations, this house could become a sought-after gem.\nWhy choose this project? It’s not just about fixing up a house; it’s about preserving local history and breathing new life into a charming relic. Are you ready to write the next chapter for this vintage brick beauty? 🏡💫",
                            ImagePath = "./images/1.jpg",
                            Name = "Vintage Brick House",
                            Price = 100000.0,
                            QuantityAvailable = 2,
                            Sale = true,
                            ShortDescription = "Your Canvas for Restoration and Timeless Transformation!"
                        },
                        new
                        {
                            Id = 2,
                            Currency = 0,
                            Description = "Nestled along the sun-kissed shoreline, this charming beachfront cabin beckons with its vintage allure. Imagine the laid-back vibes of a classic Baywatch lifeguard station—where sun, surf, and adventure collide. Despite its compact size, this cabin holds big promises for those seeking coastal magic.\nThe cabin’s picture-perfect windows frame azure waters, allowing you to watch the tides ebb and flow. Every sunrise and sunset becomes a private show. Sip your favorite drink on the deck as the sun dips below the horizon—a daily spectacle that never loses its charm. Just steps away from the shore, kick off your shoes and feel the warm sand between your toes. The beach is your backyard, and the surfboard hooks outside are ready for those exhilarating wave rides.\nWhy choose this beach haven? Channel your inner Mitch Buchannon or CJ Parker—this cabin captures that iconic coastal allure. Let the rhythmic waves soothe your soul and wash away everyday worries. Pack your sunscreen, flip-flops, and a sense of adventure. This beachfront cabin is your ticket to sun-kissed days and starlit nights. 🌴🌟",
                            ImagePath = "./images/2.jpg",
                            Name = "Baywatch Bliss",
                            Price = 1000000.0,
                            QuantityAvailable = 5,
                            Sale = true,
                            ShortDescription = "Your Seaside Retreat Awaits!"
                        },
                        new
                        {
                            Id = 3,
                            Currency = 0,
                            Description = "Nestled into the gentle curve of an earth wall, this extraordinary house seems plucked straight from the pages of a fairytale. Its round windows, like curious eyes, peer out into the world, inviting wonder and imagination. The vibrant hues of red and orange dance across its walls, as if painted by mischievous forest sprites.\nBut it’s the grass-covered roof that truly captures the heart. A living carpet of green blankets the dwelling, seamlessly merging it with the surrounding landscape. Wildflowers peek through, adding bursts of color—a secret garden hidden in plain sight.\nStep inside, and you’ll find cozy nooks and crannies, each with its own story to tell. The walls breathe ancient tales, and the hearth crackles with warmth. Fairies might flit about, tending to their tiny abode, while the scent of moss and damp earth lingers in the air.\nComplete with tiny windows that only a fairy could look through, the fairy door and irresistible cottage house-top make this a truly magical experience—if you’ll only believe. Eclectic styles and colors add to the magic, as does the pebble pathway with multi-colored flowery stepping-stones.\nWhy choose this dwelling? Because here, reality and enchantment intertwine, and every day feels like a chapter from a timeless tale. 🌿🏠✨",
                            ImagePath = "./images/3.jpg",
                            Name = "Enchanting Earth Dwelling",
                            Price = 3000000.0,
                            QuantityAvailable = 1,
                            Sale = true,
                            ShortDescription = "Where Magic Meets Reality"
                        },
                        new
                        {
                            Id = 4,
                            Currency = 0,
                            Description = "Nestled amidst the rolling countryside, this extraordinary home resides within the sturdy walls of an old windmill. Its brick exterior, weathered by time, tells tales of generations past. The circular structure, once a sentinel of the landscape, now cradles a cozy haven.\nStep through the heavy wooden door, and you’ll find yourself in a world where history and comfort intertwine. The original mill machinery—gears, cogs, and timeworn beams—stands as silent witnesses to centuries of grain-grinding labor. Sunlight filters through the round windows, casting warm patterns on the brickwork.\nThe living spaces are unconventional yet inviting. The kitchen, snug against the curved walls, boasts a hearth where meals are prepared with a touch of nostalgia. Ascend the winding staircase to the upper levels—the former milling floors—now transformed into bedrooms, each with its own nook and cranny. The views from the circular windows are nothing short of enchanting: rolling hills, swaying grass, and perhaps a distant farmhouse.\nOutside, the sails no longer turn with the wind, but the windmill’s spirit remains. The garden, bordered by ancient stones, blooms with wildflowers and herbs. A wooden bench invites contemplation, and the rustling leaves provide a soothing soundtrack.\nWhy choose this dwelling? Because it’s not just a house; it’s a living piece of history—a testament to resilience and adaptation. Here, the past whispers, and the present embraces. Are you ready to make your own mark within these sturdy brick walls? 🌾🏠✨",
                            ImagePath = "./images/4.jpg",
                            Name = "Rustic Charm",
                            Price = 1500000.0,
                            QuantityAvailable = 0,
                            Sale = false,
                            ShortDescription = "Living Inside an Ancient Brick Windmill"
                        },
                        new
                        {
                            Id = 5,
                            Currency = 0,
                            Description = "Imagine a cozy green tent, just big enough for two souls seeking adventure. Its fabric whispers tales of distant lands, and its zippers hold the promise of secret passages. Set it up wherever your heart desires—on a mountain peak, by a tranquil lake, or beneath a star-studded sky.\nFlexibility is its superpower. Fold it into your backpack, and it becomes your portable sanctuary. Unfurl it on a windswept ridge, and suddenly, you’re perched on the edge of the world. The flaps, like curious eyelids, open to reveal breathtaking vistas—the kind that make your breath catch and your spirit soar.\nAt dawn, unzip the entrance and step out onto dew-kissed grass. The world awaits: mist-shrouded valleys, ancient forests, and sun-kissed meadows. Breakfast tastes better when cooked over a tiny stove, surrounded by nature’s grandeur. And as night falls, zip up snugly, cocooned in warmth, listening to the wind weave stories through the tent’s fabric.\nWhy choose this humble abode? Because it’s not just a tent; it’s an invitation to explore. Whether you’re atop a mountain, beside a roaring river, or deep in a mystical forest, this green haven adapts. It’s where dreams merge with reality, and the stars become your ceiling.\nSo pack light, wander far, and let the green tent carry you to magnificent places. Adventure awaits—inside and out. 🌿🏕️✨",
                            ImagePath = "./images/5.jpg",
                            Name = "The Green Tent of Infinite Horizons",
                            Price = 5000.0,
                            QuantityAvailable = 2,
                            Sale = false,
                            ShortDescription = "Adventurer’s Oasis"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Webshop.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Webshop.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Webshop.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Webshop.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
